debug: true
server:
  port: 8086
  servlet:
    context-path: /
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:classpath::myDb
    username: root
    password: root


